# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    eventing.knative.dev/source: "true"
    events.cloud.run/release: devel
    events.cloud.run/crd-install: "true"
  name: pullsubscriptions.pubsub.cloud.run
spec:
  group: pubsub.cloud.run
  version: v1alpha1
  names:
    categories:
    - all
    - knative
    - pubsub
    kind: PullSubscription
    plural: pullsubscriptions
  scope: Namespaced
  subresources:
    status: {}
  additionalPrinterColumns:
    - name: Ready
      type: string
      JSONPath: ".status.conditions[?(@.type==\"Ready\")].status"
    - name: Reason
      type: string
      JSONPath: ".status.conditions[?(@.type==\"Ready\")].reason"
    - name: Age
      type: date
      JSONPath: .metadata.creationTimestamp
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          # TODO: update the OpenAPI to be much more robust.
          required:
            - sink
            - topic
          properties:
            secret:
              type: object
              # TODO: document we default.
              description: "Credential to use to poll the Cloud Pub/Sub Subscription. It is not used to create or delete the Subscription, only to poll it. The value of the secret entry must be a service account key in the JSON format (see https://cloud.google.com/iam/docs/creating-managing-service-account-keys)."
            project:
              type: string
              # TODO: document we default.
              description: "ID of the Google Cloud Project that the Pub/Sub Topic exists in. E.g. 'my-project-1234' rather than its display name, 'My Project' or its number '1234567890'."
            serviceAccountName:
              type: string
              # TODO: document we default.
              description: "Name of the Kubernetes ServiceAccount that is running the Receiver Adapter Pods."
            sink:
              type: object
              description: "Reference to an object that will resolve to a domain name to use as the sink."
            transformer:
              type: object
              description: "Reference to an object that will resolve to a domain name to use as the transformer."
            mode:
              type: string
              enum: [CloudEventsBinary, CloudEventsStructured, PushCompatible]
              description: "Mode defines the encoding and structure of the payload of when this PullSubscription invokes the sink."
            topic:
              type: string
              description: "ID of the Cloud Pub/Sub Topic to Subscribe to. It must be in the form of the unique identifier within the project, not the entire name. E.g. it must be 'laconia', not 'projects/my-gcp-project/topics/laconia'."
          type: object
        status:
          properties:
            conditions:
              items:
                properties:
                  lastTransitionTime:
                    # we use a string in the stored object but a wrapper object
                    # at runtime.
                    type: string
                  message:
                    type: string
                  reason:
                    type: string
                  severity:
                    type: string
                  status:
                    type: string
                  type:
                    type: string
                required:
                - type
                - status
                type: object
              type: array
            sinkUri:
              type: string
            transformerUri:
              type: string
            projectId:
              type: string
            subscriptionId:
              type: string
          type: object
