apiVersion: batch/v1
kind: Job
metadata:
  name: v0.16.0-upgrade
  namespace: cloud-run-events
  labels:
    events.cloud.google.com/release: devel
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      serviceAccountName: controller
      restartPolicy: Never
      containers:
      - name: upgrade-brokers
        image: ko://github.com/google/knative-gcp/cmd/upgrade/v0.16.0