apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: pubsub-push
  labels:
    events.cloud.run/release: devel
spec:
  template:
    spec:
      containers:
        - image: github.com/google/knative-gcp/cmd/pubsub/push_transformer
